### ISSUE TITLE
Could not connect to Google error message

### ISSUE THREAD

**Issue by sdrenth** [Sterc/Analytics-dashboard-widget#19]
I'm getting the following message in multiple tabs (Visitors, Sources, Search words):
Kon geen verbinding maken met Google Analytics

But some other data is being retrieved like popular pages, goals and account settings.

Has google perhaps changed the API?

**Comment by gpsietzema** [comment]
A metric was renamed by Google.

avgTimeOnSite should be: avgSessionDuration

**Comment by sdrenth** [comment]
@gpsietzema The data is now being shown in the grids, but the graphs are still not working.
