### ISSUE TITLE
Unable to authorise

### ISSUE THREAD

**Issue by markwillis82** [Sterc/Analytics-dashboard-widget#24]
I've installed this Extra and went to authorise but I receive "invalid redirect_uri" from the oAuth for "urn:ietf:wg:oauth:2.0:oob" which is the constant for the redirect uri.

Also even if I change that - i'm not sure where to change it too (seems to be that the processor mgr/settings/auth) needs to run, but then even in that processor there is a reference to `$token` which should be `$tokens` so the cached object is invalid as well.

Any help would be appreciated

**Comment by gpsietzema** [comment]
Can you show me your Analytics permissions?

**Comment by markwillis82** [comment]
I'm logging in with the same user that has access to the google console to set up the api keys. It's not the user.

**Comment by gpsietzema** [comment]
@markwillis82 I just tried it myself and had some issues as well. We somehow need to not make a web application key, but 'other':


![screen shot 2018-03-29 at 09 05 27](https://user-images.githubusercontent.com/381017/38074794-621f456e-3330-11e8-81b9-ec44ba932b30.png)

**Comment by xceed-will** [comment]
Yes were unable to 'Authorize' using a Web Application type because it throws an 'invalid client_id' error when we click Get authorization token. We had to use Other.

**Comment by sebastian-marinescu** [comment]
I've also just stumbled upon this. 

Following the link in the "Getting started" screen, I first _enabled_ the Analytics API. 
Afterwards I wanted to create the credentials and landed on a more complicated page: 

![image](https://user-images.githubusercontent.com/3798871/54970814-00d8db00-4f84-11e9-9404-5d36821d22a2.png)

To go to the more simplified and straight-forward page, a user has to actually press the dropdown-arrow on the credentials page and select "Create OAuth client ID". 

So I suggest to update the readme and the "Getting started" section from: 
> 1. First we need to create Google Analytics API credentials to be able to get data from Google Analytics.

To: 

1. First we need to enable Google Analytics API [link as before] to be able to use that API.
2. Then we need to create an OAuth client ID [link to: https://console.cloud.google.com/apis/credentials/oauthclient ] to be able to get data from Google Analytics.

**Comment by gpsietzema** [comment]
Thanks guys, we'll change it.
