### ISSUE TITLE
Access permissions and dashboard widgets should be created in resolver

### ISSUE THREAD

**Issue by sdrenth** [Sterc/Analytics-dashboard-widget#26]
The access permissions and dashboard widgets are now being created when clicking "Setup options" in the manager. So they are being created before the package is installed. These settings should be created after the package is installed using resolvers because when you are installing packages without using the manager (by using runProcessor /workspace/package/install for example) these settings are not being created.

**Comment by Oetzie** [comment]
I will fix this

**Comment by Oetzie** [comment]
Fixed in version 2.0.2.
