### ISSUE TITLE
Can't get auth token after v2.7.0

### ISSUE THREAD

**Issue by greyskymedia** [Sterc/Analytics-dashboard-widget#29]
Can't get past the setup screen. Setting up an api app id and secret is done, then adding widget to dashboard. From there I'm linked to the extra's landing page and the only button I have is "Verify Prerequisite Settings". When clicked an error logs
```[2019-05-23 14:28:24] (ERROR in modProcessor::run @ /var/www/site/core/model/modx/modprocessor.class.php : 177) Flat file processor support, used for action authenticate/verifyPrerequisite with path /var/www/site/core/components/bigbrother/processors/mgr/authenticate/verifyprerequisite.php, is deprecated since version 2.7.0. ```
Can't authorize app to get analytics in the dashboard.

**Comment by Oetzie** [comment]
@greyskymedia are you sure you are at the correct Github Repo? the error occurs in the bigbrother processor, not in a Google Analytics processor. I will close this issue.
