### ISSUE TITLE
modAction support is deprecated

### ISSUE THREAD

**Issue by tjourneylcon** [Sterc/Analytics-dashboard-widget#30]
Got the following error message while installing Google Analytics Dashboard on Revolution 2.7.2-pl
"modAction support is deprecated since version 2.3.0. Support for modAction has been replaced with routing based on a namespace and action name. Please update the extra with the namespace googleanalytics to the routing based system."

**Comment by Oetzie** [comment]
I will fix this asap.

**Comment by Oetzie** [comment]
Fixed in version 2.0.2.
