### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by lanceC-hub** [Sterc/Analytics-dashboard-widget#32]
I have several sites all running Analytics perfectly up until about a week ago.
I can revoke authorization, re-authorize no problems. Create a new GG account, new everything, authorize, no problems 
- but no stats coming in.

If i click 'Go to Google Analytics' button (after the 2 or 3 next clicks) i get to the Analytics page with all the stats.
Is this just happening to me ?
Or has something changed ?
Thanks in advance

**Comment by Oetzie** [comment]
A new version will released this week with a fix for this. A quick fix is to trim the last / from the url on line 608 in the Google Analytics Request class.

`$url = rtrim(GoogleAnalyticsRequest::API_URL, '/').'/'.rtrim($url, '/').'/';`
to
`$url = rtrim(GoogleAnalyticsRequest::API_URL, '/') . '/' . rtrim($url, '/');`

**Comment by lanceC-hub** [comment]
Ok thanks for your work & a quick reply.

**Comment by lanceC-hub** [comment]
Fix works perfectly, thanks again.

**Comment by Oetzie** [comment]
Fixed in version 2.0.2.
