### ISSUE TITLE
Revolution 3.0.0-alpha1: not work 

### ISSUE THREAD

**Issue by OlegShchavelev** [Sterc/Analytics-dashboard-widget#33]
Install widget

![изображение](https://user-images.githubusercontent.com/20732384/71778115-6f8aa080-2fba-11ea-83b1-898de5821c1c.png)

Console log

Консоль запущена...
Пробуем установить пакет с подписью: googleanalytics-2.0.2-pl
Пакет найден... сейчас идёт подготовка к его установке.
Загрузка рабочего пространства пакета...
Рабочее пространство загружено, сейчас устанавливаем пакет...
modx.modNamespace is deprecated since version 3.0. Replace references to class modx.modNamespace with MODX\Revolution\modNamespace to take advantage of PSR-4 autoloading.
modNamespace is deprecated since version 3.0. Replace references to class modNamespace with MODX\Revolution\modNamespace to take advantage of PSR-4 autoloading.
modNamespace is deprecated since version 3.0. Replace references to class modNamespace with MODX\Revolution\modNamespace to take advantage of PSR-4 autoloading.
modx.modDashboardWidget is deprecated since version 3.0. Replace references to class modx.modDashboardWidget with MODX\Revolution\modDashboardWidget to take advantage of PSR-4 autoloading.
modDashboardWidget is deprecated since version 3.0. Replace references to class modDashboardWidget with MODX\Revolution\modDashboardWidget to take advantage of PSR-4 autoloading.
modDashboardWidget is deprecated since version 3.0. Replace references to class modDashboardWidget with MODX\Revolution\modDashboardWidget to take advantage of PSR-4 autoloading.
modx.modSystemSetting is deprecated since version 3.0. Replace references to class modx.modSystemSetting with MODX\Revolution\modSystemSetting to take advantage of PSR-4 autoloading.
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => googleanalytics.branding_url )
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => googleanalytics.branding_url_help )
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => googleanalytics.account )
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => googleanalytics.client_id )
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => googleanalytics.client_secret )
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => googleanalytics.history )
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => googleanalytics.panels )
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => googleanalytics.refresh_token )
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => googleanalytics.cache_lifetime )
modx.modCategory is deprecated since version 3.0. Replace references to class modx.modCategory with MODX\Revolution\modCategory to take advantage of PSR-4 autoloading.
modCategory is deprecated since version 3.0. Replace references to class modCategory with MODX\Revolution\modCategory to take advantage of PSR-4 autoloading.
modCategory is deprecated since version 3.0. Replace references to class modCategory with MODX\Revolution\modCategory to take advantage of PSR-4 autoloading.
Attempting to preserve files at /home/users/9/9017501865/domains/modx.dtls.su/assets/components/googleanalytics into archive /home/users/9/9017501865/domains/modx.dtls.su/core/packages/googleanalytics-2.0.2-pl/modCategory/e4efa62a96e10af6e07fe7fa5e40e031.0.preserved.zip
modAccessPolicyTemplate is deprecated since version 3.0. Replace references to class modAccessPolicyTemplate with MODX\Revolution\modAccessPolicyTemplate to take advantage of PSR-4 autoloading.
modAccessPolicyTemplate is deprecated since version 3.0. Replace references to class modAccessPolicyTemplate with MODX\Revolution\modAccessPolicyTemplate to take advantage of PSR-4 autoloading.
modAccessPermission is deprecated since version 3.0. Replace references to class modAccessPermission with MODX\Revolution\modAccessPermission to take advantage of PSR-4 autoloading.
modAccessPermission is deprecated since version 3.0. Replace references to class modAccessPermission with MODX\Revolution\modAccessPermission to take advantage of PSR-4 autoloading.
modAccessPolicy is deprecated since version 3.0. Replace references to class modAccessPolicy with MODX\Revolution\modAccessPolicy to take advantage of PSR-4 autoloading.
modAccessPolicy is deprecated since version 3.0. Replace references to class modAccessPolicy with MODX\Revolution\modAccessPolicy to take advantage of PSR-4 autoloading.
modDashboard is deprecated since version 3.0. Replace references to class modDashboard with MODX\Revolution\modDashboard to take advantage of PSR-4 autoloading.
modDashboard is deprecated since version 3.0. Replace references to class modDashboard with MODX\Revolution\modDashboard to take advantage of PSR-4 autoloading.
modDashboardWidgetPlacement is deprecated since version 3.0. Replace references to class modDashboardWidgetPlacement with MODX\Revolution\modDashboardWidgetPlacement to take advantage of PSR-4 autoloading.
modDashboardWidgetPlacement is deprecated since version 3.0. Replace references to class modDashboardWidgetPlacement with MODX\Revolution\modDashboardWidgetPlacement to take advantage of PSR-4 autoloading.
transport.modTransportPackage is deprecated since version 3.0. Replace references to class transport.modTransportPackage with MODX\Revolution\Transport\modTransportPackage to take advantage of PSR-4 autoloading.
Could not find legacy class modTransportPackage after converting to MODX\Revolution\modTransportPackage
Could not load class: modTransportPackage from mysql.modtransportpackage
Could not get table name for class:
transport.modTransportPackage is deprecated since version 3.0. Replace references to class transport.modTransportPackage with MODX\Revolution\Transport\modTransportPackage to take advantage of PSR-4 autoloading.
transport.modTransportPackage is deprecated since version 3.0. Replace references to class transport.modTransportPackage with MODX\Revolution\Transport\modTransportPackage to take advantage of PSR-4 autoloading.
Error 42000 executing statement: Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS `latestPackage` WHERE `latestPackage`.`package_name` = `modTransp' at line 3 )
modx.modMenu is deprecated since version 3.0. Replace references to class modx.modMenu with MODX\Revolution\modMenu to take advantage of PSR-4 autoloading.
modMenu is deprecated since version 3.0. Replace references to class modMenu with MODX\Revolution\modMenu to take advantage of PSR-4 autoloading.
modMenu is deprecated since version 3.0. Replace references to class modMenu with MODX\Revolution\modMenu to take advantage of PSR-4 autoloading.
modAction support is deprecated since version 2.3.0. Support for modAction has been replaced with routing based on a namespace and action name. Please update the extra with the namespace sendex to the routing based system.
modAction support is deprecated since version 2.3.0. Support for modAction has been replaced with routing based on a namespace and action name. Please update the extra with the namespace gallery to the routing based system.
modAction support is deprecated since version 2.3.0. Support for modAction has been replaced with routing based on a namespace and action name. Please update the extra with the namespace orphoman to the routing based system.
modAction support is deprecated since version 2.3.0. Support for modAction has been replaced with routing based on a namespace and action name. Please update the extra with the namespace gridclasskey to the routing based system.
modAction support is deprecated since version 2.3.0. Support for modAction has been replaced with routing based on a namespace and action name. Please update the extra with the namespace gatewaymanager to the routing based system.
Успешно установлен пакет googleanalytics-2.0.2-pl

**Comment by sdrenth** [comment]
This issue has been resolved in version 3.0.0-beta
