### ISSUE TITLE
Need to update to OAuth2 by April 20

### ISSUE THREAD

**Issue by jgulledge19** [Sterc/Analytics-dashboard-widget#4]
On new install Google gives this note:
AuthSub for Google Accounts is going away. Developers should migrate to OAuth2 by April 20, 2015. Learn more: https://support.google.com/accounts/answer/6140402?hl=en

**Comment by vierkantemeter** [comment]
The Google Analytics widget doesn't work anymore since half of may 2015. 
```("Couldn't connect with google analytics")```. I guess this is caused by the AuthSub shutdown.

(There is also a forum post about this: http://forums.modx.com/thread/97136/google-analytics-dashboard-widget-no-longer-working)

I really hope Sterc is working on a update!

**Comment by crimsonpixel** [comment]
Can confirm this no longer works when trying to set up the following message received:

"Reminder: Deprecated APIs were discontinued on April 20th, 2015. To restore service, update to the replacement API."

**Comment by mikelannen** [comment]
Really wish this would be fixed so we could use it on our websites again.

**Comment by vierkantemeter** [comment]
@bumme Would it make sense if we donated a couple of euro's to speed things up? (using bountysource or paypal)

**Comment by mikelannen** [comment]
I would definitley donate.

On Sunday, May 17, 2015, Vierkante Meter <notifications@github.com> wrote:

> @bumme <https://github.com/bumme> Would it make sense if we donated a
> couple of euro's to speed things up? (using bountysource or paypal)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sterc/Analytics-dashboard-widget/issues/4#issuecomment-102859013>
> .
>


-- 



Best Regards,


*MIKE LANNEN*
Founder + Creative Director
ETERNITY WEB <http://www.EternityMarketing.com>

(802) 865-2000  x700

*We've Moved!*


182 Main Street
Studio 3
Burlington, VT 05401

**Comment by Bumme** [comment]
@jgulledge19 @vierkantemeter @crimsonpixel @mikelannen There will be an update next week ;-)

**Comment by gleighfield** [comment]
I'd also donate - publish a link up!

**Comment by mikelannen** [comment]
Great!

On Tuesday, May 19, 2015, Graeme Leighfield <notifications@github.com>
wrote:

> I'd also donate - publish a link up!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Sterc/Analytics-dashboard-widget/issues/4#issuecomment-103419309>
> .
>


-- 



Best Regards,


*MIKE LANNEN*
Founder + Creative Director
ETERNITY WEB <http://www.EternityMarketing.com>

(802) 865-2000  x700

*We've Moved!*


182 Main Street
Studio 3
Burlington, VT 05401

**Comment by Mark-H** [comment]
Big Brother is also getting an update: https://github.com/lossendae/BigBrother/issues/40

**Comment by Bumme** [comment]
There's a new release including new API and OAuth
