### ISSUE TITLE
Error when authorizing with non analytics account

### ISSUE THREAD

**Issue by MrRoco** [Sterc/Analytics-dashboard-widget#6]
When trying to authorize with a not activated analytics account i'm getting an error(blank page).

**Comment by JeffSokol** [comment]
I am currently out of the office.

If this is an urgent issue, please contact dave@ave25.com.

Otherwise, I will reply if needed when I return on Monday. Thank you for your patience. I apologize in advance for the inconvenience. 

Thanks,

Jeff Sokol

**Comment by Bumme** [comment]
@JeffSokol No it isn't. When you authenticate with an google account that doesn't have any analytics profiles you will get an error from google and the manager will be blank. 
It's just an extra validation to check if there are analytics profiles, so the manager will not be broken. 
If you use the widget with an google account that has analytics profiles (99.9% of the users that are use the widget) there will be no issues.
