### ISSUE TITLE
not working on modx 2.3.6 install

### ISSUE THREAD

**Issue by degoya** [Sterc/Analytics-dashboard-widget#7]
installed well, when i enter the authkey i can select the site and submit. then i get a 500 Server Error and the following stuff in my error log.

Stack trace:
#0 /var/www/web/core/components/analytics/model/google-api-php-client/src/Google/Client.php(120): Google_Auth_OAuth2->authenticate('xxxxxxxxxxxxxxx...')
#1 /var/www/web/core/components/analytics/elements/widget/widget.analytics.php(53): Google_Client->authenticate('xxxxxxxxxxxxxxx...')
#2 /var/www/web/core/model/modx/moddashboardwidget.class.php(72): include_once('/var/www/client...')
#3 /var/www/web/core/model/modx/moddashboard.class.php(78): modDashboardWidget->getContent(Object(WelcomeManagerController))
#4 /var/www/web/manager/controllers/default/welcome.class.php(64): modDashboard->render(Ob" while reading response header from upstream, client: x.x.x.x, server: mydomain.net, request: "POST /manager/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "mydomain.net", referrer: "http://mydomain.net/manager/"

**Comment by joeke** [comment]
Hi @degoya 
Which version did you install?
It seems that you've installed an old version of Google Analytics Dashboard. From version 1.0.3 up there's a new oAuth method, which should fix your problem.

**Comment by degoya** [comment]
Hi @joeke,

thx, i'll give it a try in the new year. 
happy hollidays.

**Comment by joeke** [comment]
@degoya
