### ISSUE TITLE
No data showing

### ISSUE THREAD

**Issue by lkfranklin** [Sterc/Analytics-dashboard-widget#9]
I've sucessfully installed an integrated the dashboard and it seems to have linked to my analytics account fine in that it's pulling through all of the projects and if I go into my system settings I can see it has populated all the fields (except sitename?). 

However no data is actually being pulled through on the dashboard as everything is set to '0'. Clicking on traffic sources I can see that it says 'Couldn't connect with google analytics'. 

Any ideas what could be wrong? 

Thanks,

**Comment by joeke** [comment]
@lkfranklin I can't seem to reproduce this behaviour. Perhaps you can re-authorize with Google Analytics? To do this, go to your system settings, and empty (do not remove) the values for 'accountId', 'profileId' ,'refreshToken' and 'webPropertyId'. After this visit your dashboard and you should see the authorize link and the authorization code form field. After authorizing with your Google account, you can select a website from the dropdown in the dashboard. Please let me know if this fixes your problem.
